// Offline pupil + teacher walk of the S1 build. Usage: node walk_s1.js <outdir> [palette]
const puppeteer = require('puppeteer'); const sharp = require('sharp'); const path = require('path');
const OUT = process.argv[2]; const PAL = process.argv[3] || 'a';
const BASE = 'http://127.0.0.1:8112/home-economics/s1-food-portfolio/';
const sleep = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  const errs = []; const br = await puppeteer.launch({ headless: 'new' });
  const pg = await br.newPage(); await pg.setViewport({ width: 1100, height: 800 });
  pg.on('pageerror', e => errs.push('pageerror: ' + e.message));
  pg.on('console', m => { if (m.type() === 'error') errs.push('console: ' + m.text()); });
  await pg.evaluateOnNewDocument(() => { try { sessionStorage.setItem('ols-intro-seen-v1', '1'); } catch (e) {} });
  const shot = async n => { await sleep(900); await pg.screenshot({ path: path.join(OUT, `walk-${PAL}-${n}.png`), fullPage: true }); };
  await pg.goto(BASE + '?reset&palette=' + PAL + '&name=' + encodeURIComponent('Aoife Murphy'), { waitUntil: 'networkidle0' }); await sleep(1500);
  await shot('01home');
  await pg.click('#new-entry'); await sleep(700);
  await pg.type('#dish-name', 'Chicken and vegetable pasta bake');
  const img = path.join(OUT, '_probe.jpg');
  await sharp({ create: { width: 800, height: 600, channels: 3, background: '#d98c4a' } }).jpeg().toFile(img);
  const fi = await pg.$('#photo-input'); await fi.uploadFile(img); await sleep(1500);
  await shot('02dish');
  await pg.click('#wiz-next'); await sleep(700);
  await pg.evaluate(() => ['crosscon', 'costing'].forEach(k => document.querySelector('[data-fk="' + k + '"]').click())); await sleep(500);
  await pg.type('[data-fp="crosscon"] textarea', 'I used a red board for the raw chicken and washed my hands straight after.');
  await pg.type('[data-ci="0"]', '2 chicken breasts'); await pg.type('[data-cc="0"]', '3.20');
  await pg.click('#cost-add'); await sleep(200); await pg.type('[data-ci="1"]', '300g pasta'); await pg.type('[data-cc="1"]', '0.60');
  await pg.type('[data-fp="costing"] textarea', 'Compared with buying it ready-made it was much cheaper per portion for a family.');
  await shot('03focus');
  await pg.click('#wiz-next'); await sleep(700);
  for (const k of ['appearance', 'taste', 'texture']) { await pg.evaluate(k => document.querySelector('.star-btn[data-sc="' + k + '"][data-sv="4"]').click(), k); await sleep(150); }
  await sleep(300);
  await pg.evaluate(() => { const a = document.querySelector('[data-mo]'); a && a.click(); });
  await sleep(300);
  await pg.evaluate(() => { const b = document.querySelector('[data-mc]'); b && b.click(); });
  await shot('04taste');
  await pg.click('#wiz-next'); await sleep(700);
  await pg.type('#www-text', 'My pasta was cooked perfectly and the sauce was smooth and creamy.');
  await pg.type('#ebi-text', 'It would have been even better with more seasoning and a crispier top.');
  await pg.type('#next-text', 'Next time I will grate the cheese finer.');
  await shot('05reflect');
  await pg.click('#entry-submit'); await sleep(2500);
  await shot('06hooray');
  const closeSel = await pg.evaluate(() => { const b = [...document.querySelectorAll('#hooray button')].find(x => /back|close|shelf|done/i.test(x.textContent)); if (b) { b.click(); return b.textContent; } return null; });
  await sleep(1200); await shot('07timeline');
  await pg.click('#staff-key'); await sleep(600); await pg.type('#staff-pass', 'demo'); await pg.click('#staff-go'); await sleep(1500);
  await shot('08staff');
  await pg.type('#staff-newclass', '11B FN'); await pg.click('#staff-add'); await sleep(2000);
  await shot('09staff-added');
  const staffText = await pg.evaluate(() => document.querySelector('#staff-classes').innerText);
  await pg.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true });
  await pg.goto(BASE + '?palette=' + PAL + '&name=' + encodeURIComponent('Aoife Murphy'), { waitUntil: 'networkidle0' }); await sleep(1500);
  await shot('10phone');
  const overflow = await pg.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  console.log(JSON.stringify({ closeSel, overflow, staffText: staffText.slice(0, 400), errs }, null, 1));
  await br.close();
})().catch(e => { console.error('FAIL', e.message); process.exit(1); });
